Sequence name:  example 

Sequence :
GGAGUCGGACGGAUCGUCGCCcCGGGGGCAACUCCGGGGAGGAAAGUCCGGGCUCCAAAGGGCAGAACGCUGGAUAACAUCCAGGGAGGGCAACCUCCGGACAGCGCCACAGAAAGCAAACCGCCCGGCCUCGGCCGGGUAAGGGUGAAACGGUGGUGUAAGAGACCACCAGAUGCCGUGGUGACACGG
 
RNA sequence

Type of Stochastic Simulation:   Co-transcriptional Fold... A new base is added every 3.000000 milliseconds.

Requested molecular time : 1000.000000 ms   (Kinefold estimation : 2000000) 

Pseudoknots:   Allowed

Entanglements:   Freely crossing

Random seed: 2977

***********************************************************************

Actual sequence folded :
GGAGUCGGACGGAUCGUCGCCCCGGGGGCAACUCCGGGGAGGAAAGUCCGGGCUCCAAAGGGCAGAACGCUGGAUAACAUCCAGGGAGGGCAACCUCCGGACAGCGCCACAGAAAGCAAACCGCCCGGCCUCGGCCGGGUAAGGGUGAAACGGUGGUGUAAGAGACCACCAGAUGCCGUGGUGACACGG

Actual Traced and Forced Helices :
T 20 39 8
T 123 140 7
T 22 100 7
T 48 128 6
T 46 102 7
